#!/usr/bin/env python

import csv
import sqlite3
import sys
import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument('-f', dest="FORCE", action="store_true")
parser.add_argument('DB_FILE')
args = parser.parse_args()

dbh = sqlite3.connect(args.DB_FILE)

in_reader = csv.reader(sys.stdin)

headers = in_reader.next()
print headers

# sanitize headers for legal SQL column names
nonwords = re.compile('[^a-zA-Z0-9_]')
columns = [ nonwords.sub('_', h) for h in headers ]

sql_create = 'create table data (' + ','.join([c + ' text' for c in columns]) + ')'
print sql_create
if args.FORCE:
    dbh.execute('drop table if exists data')
dbh.execute(sql_create)

placeholders = ['?'] * len(columns)
sql_insert = 'insert into data (' + ','.join(columns) + ') values (' + ','.join(placeholders) + ')'
print sql_insert

for row in in_reader:
    print row
    dbh.execute(sql_insert, tuple(row))

dbh.commit()
