#!/usr/bin/env python

import csv
import sqlite3
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('DB_FILE')
args = parser.parse_args()

dbh = sqlite3.connect(args.DB_FILE)

csvout = csv.writer(sys.stdout, lineterminator='\n')

cur = dbh.cursor()

# recreate the header row
headers = []
columns = []
for (h, c) in cur.execute('select header, column from headers order by position'):
    headers.append(h)
    columns.append(c)

csvout.writerow(headers)
for row in dbh.execute('select ' + ', '.join(columns) + ' from data'):
    csvout.writerow(row)
